#include "../dappservices/sign.hpp"

#define DAPPSERVICES_ACTIONS() \
  XSIGNAL_DAPPSERVICE_ACTION \
  SIGN_DAPPSERVICE_ACTIONS
#define DAPPSERVICE_ACTIONS_COMMANDS() \
  SIGN_SVC_COMMANDS() 

#define CONTRACT_NAME() signer

CONTRACT_START()

CONTRACT_END()
